### ISSUE TITLE
OLED Library doesn't work in arduino 1.8.8

### ISSUE THREAD

**Issue by 1TekPro** [Heltec-Aaron-Lee/WiFi_Kit_series#87]
@Heltec-Aaron-Lee
It does work in version 1.8.5 however. Please update the libraries.
Issues with non Lora Boards and Vext.
"LoRa Disable" in "Heltec.begin" nonfunctional.
`Heltec.begin(true /*DisplayEnable Enable*/, false /*LoRa Disable*/, true /*Serial Enable*/);`

`\heltec.cpp:88:10: error: 'Vext' was not declared in this scope  pinMode(Vext,OUTPUT);`

This can be temporarily solved locally by updating the following in "heltec.cpp"
`
void Heltec_ESP32::VextON(void)
{
#if defined( WIFI_LoRa_32_V2 ) || defined( Wireless_Stick )
	pinMode(Vext,OUTPUT);
	digitalWrite(Vext, LOW);
#elif defined( WIFI_Kit_32 )
//	pinMode(Vext,OUTPUT);
//	digitalWrite(Vext, LOW);
#endif
}

void Heltec_ESP32::VextOFF(void) //Vext default OFF
{
#if defined( WIFI_LoRa_32_V2 ) || defined( Wireless_Stick )
	pinMode(Vext,OUTPUT);
	digitalWrite(Vext, HIGH);
#elif defined( WIFI_Kit_32 )
//	pinMode(Vext,OUTPUT);
//	digitalWrite(Vext, HIGH);
#endif
}`

Also, init() seems to be a problem in OLEDDisplay.cpp
`  if (!this->connect()) {`
Seems to have something to do with the pins_arduino.h
